### ISSUE TITLE
Option for iframe usage?

### ISSUE THREAD

**Issue by ghost** [maiyaporn/summernote-map-plugin#1]
Do you know if it's possible to embed maps without using iframe's?

**Comment by maiyaporn** [comment]
As far as I know, there are only two ways for using embed maps - iframe or api. Since api requires javascript, so I decided to use an iframe. Is there any specific issue with using iframe in Summernote?

Another option would be to use [Google Static Maps API](https://developers.google.com/maps/documentation/static-maps/intro) which will be inserted in Summernote as img.

**Comment by ghost** [comment]
Your right, I just had a quick look around about this. Google not long ago allowed embedding with different options.

Using iFrames within pages is considered a security risk, and search engines don't like them much either, although having a map feature is a great idea, it's just a shame Google doesn't give more options for embedding.

**Comment by maiyaporn** [comment]
So does this mean that we shouldn't have a map plugin?

**Comment by ghost** [comment]
Not at all, I like the plugin, I think it's a great plugin. Was just suggesting a different way to add maps to into the editor that will end up being displayed on the front end.

I find it quite perplexing though, that Google doesn't recommend iframes on indexable content, yet have iframes as the only easy option (without using their API) to embed maps.

**Comment by maiyaporn** [comment]
I agree that google should have another option other than using iframe. All we can do is to wait for a better way. For now, I'm thinking about allowing users to choose between embed map(iframe) or static map(image) in case of security concerns.

**Comment by ghost** [comment]
Options are always good. I'm sure what you do will be awesome.
